### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by 1cedsoda** [miguelmota/arraybuffer-to-audiobuffer#1]
```javascript
(node:20013) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at Promise (/home/x/y/z/node_modules/arraybuffer-to-audiobuffer/arraybuffer-to-audiobuffer.js:12:9)
    at new Promise (<anonymous>)
    at arrayBufferToAudioBuffer (/home/x/y/z/node_modules/arraybuffer-to-audiobuffer/arraybuffer-to-audiobuffer.js:5:12)
    at PassThrough.mic.audioStream.on (/home/x/y/z/index.js:18:3)
    at PassThrough.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at PassThrough.Readable.push (_stream_readable.js:219:10)
    at PassThrough.Transform.push (_stream_transform.js:151:32)
    at PassThrough.afterTransform (_stream_transform.js:92:10)
(node:20013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20013) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by miguelmota** [comment]
@phyyyl can you provide the code you're using that generated the error?

keep in mind that is library is targeted only for browser environments

**Comment by miguelmota** [comment]
Please reopen issue if problem persists with the latest release
